# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('metrics', models.CharField(choices=[(b'Rainfall', b'Rainfall'), (b'Tmax', b'Tmax'), (b'Tmin', b'Tmin')], max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Location')),
            ],
            options={
                'db_table': 'measure',
            },
        ),
    ]
